In [1]:
from scipy import signal as sig
import numpy as np

In [2]:
x = [1, 1, 2, 3]
y = x

In [3]:
cor = []

for l in range(-max(len(x), len(y)), max(len(x), len(y))):
    sigma = 0
    for n in range(len(x)):
        if n - l < len(y) and n - l >= 0:
            sigma += x[n] * y[n - l]
        else:
            sigma += 0
    cor.append(sigma)

In [4]:
cor_xy = []

for item in cor:
    if not item == 0:
        cor_xy.append(item)


In [5]:
cor_xy = np.array(cor_xy)
cor_xy

array([ 3,  5,  9, 15,  9,  5,  3])

In [6]:
def auto_correlate(x):
    y = x
    cor = []

    for l in range(-max(len(x), len(y)), max(len(x), len(y))):
        sigma = 0
        for n in range(len(x)):
            if n - l < len(y) and n - l >= 0:
                sigma += x[n] * y[n - l]
            else:
                sigma += 0
        cor.append(sigma)
    
    cor_xy = []

    for item in cor:
        if not item == 0:
            cor_xy.append(item)
    return np.array(cor_xy)

In [7]:
auto_correlate(x)

array([ 3,  5,  9, 15,  9,  5,  3])

In [8]:
sig.correlate(x, x)

array([ 3,  5,  9, 15,  9,  5,  3])