In [1]:
from scipy import signal as sig
import numpy as np

In [2]:
x = [1, 1, 1, 1, 1, 1.5, 1, 1, 1]
y = [1, 1, 0, 0, 0, 0.9, 1, 1, 1]

In [3]:
conv = []

for l in range(-2 * max(len(x), len(y)), 2 * max(len(x), len(y))):
    sigma = 0
    for n in range(len(x)):
        if -n + l < len(y) and -n + l >= 0:
            sigma += x[n] * y[-n + l]
        else:
            sigma += 0
    conv.append(sigma)

In [4]:
conv_xy = []

for item in conv:
    if not item == 0:
        conv_xy.append(item)

conv_xy = np.array(conv_xy)

In [5]:
conv_xy

array([1.  , 2.  , 2.  , 2.  , 2.  , 3.4 , 4.4 , 4.9 , 5.9 , 4.9 , 4.35,
       4.4 , 4.4 , 4.4 , 3.  , 2.  , 1.  ])

In [6]:
def convolve(x,y):
    conv = []

    for l in range(-2 * max(len(x), len(y)), 2 * max(len(x), len(y))):
        sigma = 0
        for n in range(len(x)):
            if -n + l < len(y) and -n + l >= 0:
                sigma += x[n] * y[-n + l]
            else:
                sigma += 0
        conv.append(sigma)
    
    conv_xy = []

    for item in conv:
        if not item == 0:
            conv_xy.append(item)

    return np.array(conv_xy)

In [7]:
convolve(x,y)

array([1.  , 2.  , 2.  , 2.  , 2.  , 3.4 , 4.4 , 4.9 , 5.9 , 4.9 , 4.35,
       4.4 , 4.4 , 4.4 , 3.  , 2.  , 1.  ])

In [8]:
sig.convolve(x, y)

array([1.  , 2.  , 2.  , 2.  , 2.  , 3.4 , 4.4 , 4.9 , 5.9 , 4.9 , 4.35,
       4.4 , 4.4 , 4.4 , 3.  , 2.  , 1.  ])