In [12]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft, fftfreq, ifft

In [20]:
def idft(Signal):
    N = len(Signal)
    X = []
    for k in range(N):
        sumc = 0
        for n in range(N):
            ang = 2*np.pi*k*n/N
            sumc += Signal[n]*(np.cos(ang) + 1j*np.sin(ang))/N
        X.append(sumc)
    return X

In [29]:
idft([ 1,  -1j,
      -1,   1j])

[0j,
 (1-9.184850993605148e-17j),
 (-3.633735870479366e-17+5.551115123125783e-17j),
 9.18485099360515e-17j]

In [26]:
np.abs(idft([ 1,  -1j,
             -1, 1j]))

array([0.00000000e+00, 1.00000000e+00, 6.63467524e-17, 9.18485099e-17])

In [27]:
ifft([ 1,  -1j,
      -1,   1j])

array([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j])

In [28]:
np.abs(ifft([ 1,  -1j,
      -1, 1j]))

array([0., 1., 0., 0.])